services:
  - type: web
    name: video-downloader
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.13
      - key: PORT
        value: 5000
      # Spotify API credentials - set these in the Render dashboard as secrets
      - key: SPOTIFY_CLIENT_ID
        sync: false
      - key: SPOTIFY_CLIENT_SECRET
        sync: false
      # Optional: if you have an OAuth Bearer token (eg from user auth or long-lived token),
      # you can provide it here to fetch previews without client credentials
      - key: SPOTIFY_BEARER_TOKEN
        sync: false
    disk:
      name: downloads
      mountPath: /app/static/downloads
      sizeGB: 1
